######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 30 21:52:25 2010
######################################################################

TEMPLATE = app
TARGET = stretchplayer
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += debug

LIBS += -ljack -lsndfile -lsamplerate

# Input
HEADERS += PlayerWidget.hpp Engine.hpp
SOURCES += main.cpp PlayerWidget.cpp Engine.cpp
