######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 30 21:52:25 2010
######################################################################

TEMPLATE = app
TARGET = stretchplayer
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += PlayerWidget.hpp
SOURCES += main.cpp PlayerWidget.cpp
